Fixes #24 - Creating pdf documents
open-zaak/cmis-adapter pull request #25
Opened 2020-11-04 13:34 UTC by SilviaAmAm

Fixes #24 

PDF documents can also be created now without causing an error.

2020-11-04 17:15 UTC, joeribekker approved these changes

2020-11-04 17:16 UTC, joeribekker commented
@sergei-maertens Can you do a sanity check here

2020-11-06 09:47 UTC, sergei-maertens requested changes
As discussed on Slack - the changing return time from `def request` (was `str`, is now `bytes`) is not ideal:

1. All previous code has been written with `str` objects in mind, so I'm not very confident that it will handle `bytes` without problems
2. The `bytes` return data is only relevant for the SOAP calls where you retrieve the file content - other calls (the majority) are plain XML that's UTF-8 encoded

The proposed solution is to add an argument `keep_binary=False` to `def request`. If the value is `False`, the soap_response content is decoded from `bytes` to `str`. If the value is `True`, you get the plain `bytes` object.

This will require the type hint to change from `-> str` to `-> Union[str, bytes]` too.

2020-11-06 12:40 UTC, sergei-maertens requested changes

2020-11-06 12:40 UTC, sergei-maertens commented on drc_cmis/webservice/request.py
> +        keep_binary: Optional[bool] = False,
`Optional` means effectively `Union[None, <type>]` - in this case, we don't expect `None` as value as all.

```suggestion
        keep_binary: bool = False,
```

2020-11-06 13:14 UTC, sergei-maertens approved these changes

2020-11-06 13:24 UTC, merged